'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System.Collections.Generic

Namespace WPFDataGridGettingStartedNETFramework

    Public Partial Class CustomerDemographic

        <System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")>
        Public Sub New()
            Customers = New HashSet(Of Customer)()
        End Sub

        Public Property CustomerTypeID As String

        Public Property CustomerDesc As String

        <System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")>
        Public Overridable Property Customers As ICollection(Of Customer)
    End Class
End Namespace
